# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "production" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.0.0
        with: 
          python-version: 3.7
      # Runs a set of commands using the runners shell
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install talib
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
              && sudo tar -xzf ta-lib-0.4.0-src.tar.gz \
              && sudo rm ta-lib-0.4.0-src.tar.gz \
              && cd ta-lib/ \
              && sudo ./configure --prefix=/usr \
              && sudo make \
              && sudo make install \
              && cd ~ \
              && sudo rm -rf ta-lib/ \
              && pip install ta-lib
      - name: Run test
        run: |
          cd src
          pytest main.py
