name: binance-trading

on: [push]

jobs: 
  run:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - name: Run the project
        run: |
          #pip install -r requirements.txt
          python src/paper_trading.py
